from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class InitStoryResult:
    directory: Path
    scenes_path: Path
    readme_path: Path


_TEMPLATE_README = """# Your Story

This folder was generated by `btg init-story`.

## Run

From the repo root (or anywhere that has `btg` installed):

```bash
btg play --scenes ./scenes.yaml
```

## Validate (recommended)

```bash
btg lint --strict --scenes ./scenes.yaml
```

## Edit

Open `scenes.yaml` in a text editor and start writing.

Tips:
- Keep scene ids in `lower_snake_case`.
- Use `terminal: true` on endings.
- Use `flags` + `requires_flags` to unlock memory threads.
"""


_TEMPLATE_SCENES = """schema_version: 1
title: "{title}"
start: intro

# Declare flags you plan to use in this story.
flags:
  - took_photo

scenes:
  - id: intro
    text: |
      You are standing at the edge of a moment.
      Pick one small action and let the story follow it.

    choices:
      - label: "Pick up the photo."
        goto: kitchen
        sets_flags: [took_photo]
        delta: { warmth: +1 }

      - label: "Walk straight into the kitchen."
        goto: kitchen
        delta: { energy: -1 }

  - id: kitchen
    text: |
      The kitchen is brighter than you expected.
      The air holds the quiet hum of ordinary life.

    choices:
      - label: "Look at the photo again."
        goto: end
        requires_flags: [took_photo]
        delta: { warmth: +1 }

      - label: "Sit at the table and breathe."
        goto: end
        delta: { support: +1 }

  - id: end
    terminal: true
    text: |
      End of the starter story.

      Next:
      - Add a new scene id under `scenes:`
      - Point a `goto:` at it
      - Keep running `btg lint --strict` as you iterate
"""


def _write_text(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise ValueError(f"Refusing to overwrite existing file: {path}")
    path.write_text(content, encoding="utf-8")


def init_story(directory: Path, *, title: str, force: bool = False) -> InitStoryResult:
    """Create a starter story folder with README.md and scenes.yaml.

    If `directory` exists, we only overwrite files when `force=True`.
    """
    directory = directory.expanduser()
    directory.mkdir(parents=True, exist_ok=True)

    scenes_path = directory / "scenes.yaml"
    readme_path = directory / "README.md"

    _write_text(readme_path, _TEMPLATE_README, force=force)

    # IMPORTANT: Use plain replace, not str.format(), because the YAML contains braces like
    # `delta: { warmth: +1 }` which would be interpreted as format placeholders.
    safe_title = title.strip() or "Your Story"
    scenes_text = _TEMPLATE_SCENES.replace("{title}", safe_title)

    _write_text(scenes_path, scenes_text, force=force)

    return InitStoryResult(directory=directory, scenes_path=scenes_path, readme_path=readme_path)
